apiVersion: v1
kind: ConfigMap
metadata:
  name: educational-management-config
  namespace: educational-management
data:
  NODE_ENV: "production"
  PORT: "3001"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "educational_management"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  LOG_LEVEL: "warn"
  LOG_FILE: "/app/logs/app.log"
  MAX_FILE_SIZE: "10485760"
  UPLOAD_PATH: "/app/uploads"




