apiVersion: apps/v1
kind: Deployment
metadata:
  name: educational-management-app
  namespace: educational-management
  labels:
    app: educational-management
    component: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: educational-management
      component: app
  template:
    metadata:
      labels:
        app: educational-management
        component: app
    spec:
      containers:
      - name: app
        image: educational-management:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: educational-management-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: educational-management-config
              key: PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: educational-management-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: educational-management-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: educational-management-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: educational-management-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: educational-management-secrets
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: educational-management-secrets
              key: JWT_SECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: educational-management-secrets
              key: JWT_REFRESH_SECRET
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: educational-management-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: educational-management-config
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: educational-management-secrets
              key: REDIS_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: app-uploads
          mountPath: /app/uploads
        - name: app-logs
          mountPath: /app/logs
      volumes:
      - name: app-uploads
        persistentVolumeClaim:
          claimName: app-uploads-pvc
      - name: app-logs
        persistentVolumeClaim:
          claimName: app-logs-pvc
      restartPolicy: Always




