apiVersion: v1
kind: Service
metadata:
  name: educational-management-service
  namespace: educational-management
  labels:
    app: educational-management
spec:
  selector:
    app: educational-management
    component: app
  ports:
  - name: http
    port: 80
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: educational-management
  labels:
    app: educational-management
    component: postgres
spec:
  selector:
    app: educational-management
    component: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: educational-management
  labels:
    app: educational-management
    component: redis
spec:
  selector:
    app: educational-management
    component: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP




