version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: educational_postgres
    environment:
      POSTGRES_DB: educational_system
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - educational_network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: educational_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - educational_network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Application (for production)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: educational_app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://admin:password@postgres:5432/educational_system
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - educational_network
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  educational_network:
    driver: bridge













